spring.application.name=ordering

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-patient-surf-ah1movg4-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_R0xkaWMJPq8O}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

razorpay.key.id=rzp_live_Sjob3tTlrGrG0X
razorpay.key.secret=p3xDamIcyPYvVoY8eWwnGQSj
razorpay.mock=false

server.port=8080

# Allow large base64 image payloads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.mvc.async.request-timeout=60000
